### ISSUE TITLE
希望可以根据字幕名字修改电影名字

### ISSUE THREAD

**Issue by lingbaoboy** [qwqcode/SubRenamer#12]
希望可以根据字幕名字修改电影名字，因为有的字幕有剧集标题，资料反而更全

**Comment by qwqcode** [comment]
https://github.com/qwqcode/SubRenamer/releases/tag/0.5.0

![image](https://user-images.githubusercontent.com/22412567/116822768-56e0c980-abb3-11eb-8943-067eedf376d2.png)
