### ISSUE TITLE
增加语言后缀支持

### ISSUE THREAD

**Issue by Xm798** [qwqcode/SubRenamer#18]
某些资源下载的字幕存在多语言，一般是通过添加形如.chs .cht .eng的后缀实现，希望添加字幕多语言的支持。

**Comment by qwqcode** [comment]
你好，新版 v2.0.0 程序已增加多语言识别筛选功能，感谢反馈！

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/96b93f6e-aba6-4a52-b6fb-7e4764cb6d4e)
