### ISSUE TITLE
不要限制字幕格式

### ISSUE THREAD

**Issue by necan** [qwqcode/SubRenamer#21]
该软件只需重命名即可，不必限制字幕格式，比如 txt、vtt 等，

**Comment by BaronzzzZ** [comment]
用vs导入项目，修改Global.cs中的参数，重新生成一下就行（我需要添加.sup的文件类型，已成功）

**Comment by qwqcode** [comment]
你好，新版 v2.0.0 支持自定义扩充识别文件后缀的功能，你可以将 vtt 加入到设置界面的「字幕格式扩充」输入框中，感谢反馈！

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/adc6880e-482e-4e1b-a1f9-78fd5445d2fa)

我已将 txt 文件加入到程序代码中，有需要可以修改并重新编译：

https://github.com/qwqcode/SubRenamer/blob/main/SubRenamer/Common/Constants.cs#L8-L9
