### ISSUE TITLE
xml 格式支持

### ISSUE THREAD

**Issue by pspbra** [qwqcode/SubRenamer#25]
关于字幕的格式，似乎不支持xml文件，希望能够支持，我本地保存有对应番剧的弹幕文件，通常为xml格式，希望能够对应匹配

**Comment by qwqcode** [comment]
你好，新版 v2.0.0 支持自定义扩充识别文件后缀的功能，你可以将 `xml` 加入到设置界面的「字幕格式扩充」输入框中，感谢反馈！

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/b25184e9-8ce3-40e6-b469-751f6af1c53c)
