### ISSUE TITLE
希望增加自定义正则时的样例，或者按照顺序进行匹配

### ISSUE THREAD

**Issue by hurriedlu** [qwqcode/SubRenamer#29]
如题，在正则表达式测试网页内可以正常匹配：
![image](https://user-images.githubusercontent.com/84308195/212998553-dfded702-2322-42f3-b7c2-65475a1ec559.png)
但回到应用内发现匹配不上，不知道是写的有问题还是格式不对，第一次接触正则，不确定写的是不是有bug。重新匹配的按钮也按过，但好像没变化（除了卡了一下）
![image](https://user-images.githubusercontent.com/84308195/212999343-45915015-5adf-4512-b7ac-4e68abf130da.png)

一般来说，下载的视频和字幕的命名都是按照一定顺序排列的，可不可以加个按照顺序匹配的设置？

**Comment by gzyguo** [comment]
对，最简单的顺序模式，来一个，最好能高亮有匹配错嫌疑的
