### ISSUE TITLE
希望能增加 Dark Mode & 加入後綴功能

### ISSUE THREAD

**Issue by snoopyzx963** [qwqcode/SubRenamer#31]
希望能增加 
1. Dark Mode
2. 加入後綴功能(Ex. .cht.ass, chs.ass, 自行輸入.srt)

好用的軟體，非常感謝作者！

**Comment by cqboyone** [comment]
我也是这样想的。留下了不懂c#的泪水。

**Comment by qwqcode** [comment]
你好，新版 v2.0.0 已增加 Dark Mode，并且增加识别和筛选 `cht.ass`，`chs.ass` 的功能，感谢反馈！

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/7b9dc771-d516-4479-946a-30c5a4f46c6b)

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/6a063bea-a7c9-4ae9-8b85-1af2dfd11471)
