### ISSUE TITLE
希望增加个新功能：批量修改字幕时间轴

### ISSUE THREAD

**Issue by share18x** [qwqcode/SubRenamer#33]

**Comment by share18x** [comment]
从网上下载的字幕有些和视频文件的对话时间轴对不上，一个个改特麻烦，希望可以出一个tool批量修改

**Comment by NekomiAyase** [comment]
字幕移轴目前可以用aegisub

**Comment by qwqcode** [comment]
v2.3.0 已增加自动调整字幕时间轴功能

https://github.com/qwqcode/SubRenamer?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E8%B0%83%E8%BD%B4
