### ISSUE TITLE
希望增加字幕文件语言后缀功能

### ISSUE THREAD

**Issue by StriverLite** [qwqcode/SubRenamer#35]
对于字幕，可能有一对多的情况，一般多字幕命名规则举例如下：

Example.1:
- Movie: [Name].avi
- English Subtitles:[Name].en.srt
- French Subtitles: [Name].fr.srt
- Spanish Subtitles: [Name].es.srt

Example.2:
- AAA.zh.ass
- AAA.zh.default.ass

**Comment by qwqcode** [comment]
你好，新版 v2.0.0 已新增支持筛选多种后缀的字幕文件功能，感谢反馈！

![image](https://github.com/qwqcode/SubRenamer/assets/22412567/301c559f-404b-4363-bd8b-ffa1281d6675)
