### ISSUE TITLE
希望可以自定义重命名后字幕的后缀格式

### ISSUE THREAD

**Issue by github-xihe** [qwqcode/SubRenamer#38]
比如：无职转生 ～到了异世界就拿出真本事～ (2021) S01E01.mkv  有简繁两种字幕
字幕重命名前：
Mushoku Tensei ～Isekai Ittara Honki Dasu～ [01][Ma10p_1080p][x265_flac].SC.ass
Mushoku Tensei ～Isekai Ittara Honki Dasu～ [01][Ma10p_1080p][x265_flac].TC.ass
字幕重命名后：
无职转生 ～到了异世界就拿出真本事～ (2021) S01E01.chs.ass
无职转生 ～到了异世界就拿出真本事～ (2021) S01E01.cht.ass
可以重命名后保留简繁两种格式

**Comment by hatulaile** [comment]
我建议可以选择:
保留语言后缀 或者 自定义语言后缀的替换
与 无语言后缀 添加后缀
### 如:
当字幕文件为 `S01E01.chs.ass` 有两种选择
1.保留原语言代码 重命名为 `XXX.S01E01.chs.ass`
2.自义定替换语言代码 `chs->zh-cn` 重命名为 `XXX.S01E01.zh-cn.ass`
