### ISSUE TITLE
编译错误：fatal error LNK1181

### ISSUE THREAD

**Issue by kiririto** [qwqcode/SubRenamer#46]
不好意思请问下，用dotnet publish命令编译出现下列错误，请问会是什么原因呢？
是缺少nuget包吗？还是环境配置有问题

PS E:\Programming\source\repos\SubRenamer\SubRenamer> dotnet publish -r win-x64 -c Release
  Determining projects to restore...
  所有项目均是最新的，无法还原。
  SubRenamer -> E:\Programming\source\repos\SubRenamer\SubRenamer\bin\Release\net8.0\win-x64\SubRenamer.dll
LINK : fatal error LNK1181: 无法打开输入文件“native\libHarfBuzzSharp.lib” [E:\Programming\source\repos\SubRenamer\SubRenamer\Su
bRenamer.csproj]
C:\Users\liuzu\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.6\build\Microsoft.NETCore.Native.targets(370,5): error M
SB3073: 命令“"C:\Program\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\link.exe" @"obj
\Release\net8.0\win-x64\native\link.rsp"”已退出，代码为 1181。 [E:\Programming\source\repos\SubRenamer\SubRenamer\SubRenamer.cs
proj]

VS安装配置如下
![image](https://github.com/qwqcode/SubRenamer/assets/49472216/305e0f66-8047-4dcb-877f-4e2a261d608a)

**Comment by qwqcode** [comment]
在 Win 平台为了构建出单个 exe 文件，无额外的 dll，所以做了特殊处理。

可以暂时删掉 `SubRenamer/SubRenamer.csproj` 文件中的：

```xml
<ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
        <DirectPInvoke Include="libHarfBuzzSharp" />
        <NativeLibrary Include="native\libHarfBuzzSharp.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
        <DirectPInvoke Include="libSkiaSharp" />
        <NativeLibrary Include="native\libSkiaSharp.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
        <DirectPInvoke Include="av_libglesv2" />
        <NativeLibrary Include="native\av_libglesv2.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
    </ItemGroup>
```

然后重试编译

**Comment by kiririto** [comment]
非常感谢！我试试

**Comment by kiririto** [comment]
Directory: E:\Programming\source\repos\SubRenamer\SubRenamer\bin\Release\net8.0\win-x64\publish

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           2020/9/19     9:46        4369408 av_libglesv2.dll
-a---           2024/4/10     2:25        1607216 libHarfBuzzSharp.dll
-a---           2024/1/11     7:47        9414064 libSkiaSharp.dll
-a---           2024/6/24    19:59       57023488 SubRenamer.exe
-a---           2024/6/24    19:59      321826816 SubRenamer.pdb

发布成功了，非常感谢，不过还想问下为什么大小比release版本大几十兆呢？

**Comment by qwqcode** [comment]
因为用了 upx 压缩

**Comment by kiririto** [comment]
原来如此！感谢回答
