### ISSUE TITLE
macOS version v2.3.0 installation failed

### ISSUE THREAD

**Issue by vizmoe** [qwqcode/SubRenamer#71]
Installation of SubRenamer v2.3.0 on M4 mac failed. After downloading SubRenamer_macos_arm64.zip and extracting, a warning displayed that “SubRenamer” is damaged and can’t be opened. You should move it to the Trash.

**Comment by qwqcode** [comment]
Refer to the FAQ section of the README.md:

```md
Cannot open on macOS, prompts as damaged

There are many solutions available online. Here's one method: enter the following command in the terminal:

> sudo xattr -d com.apple.quarantine /Applications/SubRenamer.app

The reason is that the app is not signed by an Apple developer. macOS will flag it as damaged, and registering a developer account costs $99/year.
```

If possible, contributions to support a developer account for signing SubRenamer are welcome. 😄

---

Chinese (Simplified)：

参考 README.md 的 FAQ 部分：

```md
macOS 无法打开，提示已损坏

网上可以找到很多解决的方法，这里提供一个方法，在终端中输入以下命令：

> sudo xattr -d com.apple.quarantine /Applications/SubRenamer.app

原因是没有经过苹果开发者签名，macOS 会提示已损坏，而注册开发者账号需要 99 美元/年。
```

<img width="937" alt="SCR-20241210-rrln" src="https://github.com/user-attachments/assets/5da59026-2974-4c58-aa4e-e5074dcd58cd">
