### ISSUE TITLE
建议自动匹配加入大小写模糊匹配

### ISSUE THREAD

**Issue by terrytw** [qwqcode/SubRenamer#9]
如DARK.S01E09.Everything.Is.Now.1080p

和DARK.S01E09.Everything.is.Now.1080p

不能自动匹配

手动模式可以匹配，但是软件做出来目的就是偷懒不是么=.=
谢谢作者！

**Comment by qwqcode** [comment]
非常感谢您的反馈！😆

由于一些疏忽，导致某些情况无法正确匹配... 原因已查明：

https://github.com/qwqcode/SubRenamer/commit/2b672dc89f9590768afb4fd3563c3f0864e69538#r49949621

🤣🤣🤣

### 之前的版本：
![](https://user-images.githubusercontent.com/22412567/115967911-cdece100-a567-11eb-9711-b5e0b3b9aca9.png)

### 修复后：
![](https://user-images.githubusercontent.com/22412567/115967923-d2b19500-a567-11eb-8390-fd82ac36c246.png)

**Comment by terrytw** [comment]
作者你网站证书过期了🤣
